#!/bin/bash
red='\e[1;31m'
green='\e[1;32m'
blue='\e[1;34m'
purple='\e[1;35m'
cyan='\e[1;36m'
white='\e[1;37m'
yellow='\e[1;33m'
echo -e $green '==============================================================================='
echo ""
echo -e $yellow '         ████████╗    ██████╗   ██████╗  ██╗      ███████╗       ██╗  ██╗██╗  ██╗  '
echo -e $yellow '         ╚══██╔══╝   ██╔═══██╗ ██╔═══██╗ ██║      ██╔════╝       ██║  ██║██║ ██╔╝  '
echo -e $yellow '            ██║      ██║   ██║ ██║   ██║ ██║      ███████╗ █████╗███████║█████╔╝   '
echo -e $green  '            ██║      ██║   ██║ ██║   ██║ ██║      ╚════██║ ╚════╝██╔══██║██╔═██╗   '
echo -e $green  '            ██║      ╚██████╔╝ ╚██████╔╝ ███████╗ ███████║       ██║  ██║██║  ██╗  '
echo -e $green  '            ╚═╝       ╚═════╝   ╚═════╝  ╚══════╝ ╚══════╝       ╚═╝  ╚═╝╚═╝  ╚═   '
echo ""
echo -e $white  "CopyRights : CyberSecurity : Mohammed Al-Shameri | Yemen | github.com/profionaldhim"
echo ""
echo ""
echo -e $white  "Youtube : Mohammed Al-Shameri"
echo ""
echo -e $green  '=============================================================================='
